[package]
name = "rinha-backend-2023-q3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6"
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["json"]}
serde = { version = "1.0.185", features = ["derive"] }
ulid = { version = "1.0.0", features = ["serde"] }
chrono = { version = "0.4.26", features = ["serde"] }
